from fastapi import APIRouter, Depends, HTTPException, status, Query
from fastapi.responses import Response
from sqlalchemy.orm import Session
from sqlalchemy import func
from typing import List, Optional
from datetime import date, datetime, timedelta
from dateutil.relativedelta import relativedelta
import logging
import io

from app.database import get_db
from app.models.asset import Asset, Category, AssignmentHistory
from app.models.employee import Employee
from app.models.user import User
from app.models.supplier import Supplier
from app.models.warranty import Warranty
from app.models.component import Component, AssetComponentHistory, ComponentStatus
from app.schemas.asset import (
    AssetCreate, AssetUpdate, AssetAssign, AssetResponse, AssetListResponse,
    CategoryCreate, CategoryResponse,
    DashboardMetrics, WarrantyAlert, AssignmentHistoryResponse,
    AssetReportRequest, AssetProfileReportRequest
)
from app.schemas.component import InstallComponentRequest, AssetComponentHistoryResponse, RemoveComponentRequest
from app.dependencies import get_current_user

router = APIRouter(prefix="/api/v1/assets", tags=["assets"])
logger = logging.getLogger(__name__)


def _generate_assets_pdf_with_reportlab(
    report_title: str,
    generated_by: str,
    filters: dict,
    fields,
    assets: List[Asset],
    summary: dict,
) -> bytes:
    """Fallback PDF generator using ReportLab (no GTK runtime required)."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
    )

    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph(f"<b>{report_title}</b>", styles["Title"]))
    elements.append(
        Paragraph(
            f"Generated by: {generated_by} | Generated at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            styles["Normal"],
        )
    )
    elements.append(
        Paragraph(
            (
                f"Filters - Status: {filters.get('status', 'all')} | "
                f"From: {filters.get('start_date') or 'Any'} | To: {filters.get('end_date') or 'Any'}"
            ),
            styles["Normal"],
        )
    )
    elements.append(Spacer(1, 6))

    summary_data = [
        [
            "Total Assets",
            "Assigned",
            "Unassigned",
            "Total Value",
            "Available",
            "Deployed",
            "In Maintenance",
            "Retired",
            "Disposed",
        ],
        [
            str(summary.get("total_assets", 0)),
            str(summary.get("assigned_assets", 0)),
            str(summary.get("unassigned_assets", 0)),
            f"LKR {summary.get('total_value', 0):.2f}",
            str(summary.get("status_counts", {}).get("Available", 0)),
            str(summary.get("status_counts", {}).get("Deployed", 0)),
            str(summary.get("status_counts", {}).get("In Maintenance", 0)),
            str(summary.get("status_counts", {}).get("Retired", 0)),
            str(summary.get("status_counts", {}).get("Disposed", 0)),
        ],
    ]
    summary_table = Table(summary_data, repeatRows=1)
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    elements.append(summary_table)
    elements.append(Spacer(1, 10))

    headers = ["Asset Tag"]
    if fields.include_serial_number:
        headers.append("Serial")
    if fields.include_category:
        headers.append("Category")
    if fields.include_model:
        headers.append("Model")
    headers.append("Status")
    if fields.include_assignee:
        headers.append("Assignee")
    if fields.include_supplier:
        headers.append("Supplier")
    if fields.include_purchase_date:
        headers.append("Purchase Date")
    if fields.include_purchase_price:
        headers.append("Price (LKR)")
    if fields.include_warranty:
        headers.append("Warranty")
    if fields.include_location:
        headers.append("Location")
    if fields.include_notes:
        headers.append("Notes")

    table_rows = [headers]
    for asset in assets:
        row = [asset.asset_tag]
        if fields.include_serial_number:
            row.append(asset.serial_number or "-")
        if fields.include_category:
            row.append(asset.category.name if asset.category else "-")
        if fields.include_model:
            row.append(f"{asset.manufacturer} {asset.model_name}")
        row.append(asset.status)
        if fields.include_assignee:
            row.append(asset.employee.name if asset.employee else "Unassigned")
        if fields.include_supplier:
            row.append(asset.supplier.name if asset.supplier else "-")
        if fields.include_purchase_date:
            row.append(asset.purchase_date.strftime("%Y-%m-%d") if asset.purchase_date else "-")
        if fields.include_purchase_price:
            row.append(f"LKR {asset.purchase_price:.2f}" if asset.purchase_price else "-")
        if fields.include_warranty:
            row.append(asset.warranty_expiry_date.strftime("%Y-%m-%d") if asset.warranty_expiry_date else "-")
        if fields.include_location:
            row.append(asset.location or "-")
        if fields.include_notes:
            row.append(asset.notes or "-")
        table_rows.append(row)

    if len(table_rows) == 1:
        table_rows.append(["No assets matched selected filters"] + [""] * (len(headers) - 1))

    report_table = Table(table_rows, repeatRows=1)
    report_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ]
        )
    )
    elements.append(report_table)

    doc.build(elements)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf


def _generate_asset_profile_pdf_with_reportlab(
    report_title: str,
    generated_by: str,
    asset: Asset,
    assignment_history: List[AssignmentHistory],
    component_history: List[AssetComponentHistory],
    fields,
) -> bytes:
    """Generate a single-asset lifecycle PDF report using ReportLab."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

    def _fmt_date(value):
        if not value:
            return "-"
        if isinstance(value, (datetime, date)):
            return value.strftime("%Y-%m-%d")
        return str(value)

    def _fmt_money(value):
        if value is None:
            return "-"
        return f"LKR {value:.2f}"

    def _is_warranty_active() -> bool:
        if asset.warranty and asset.warranty.end_date:
            return asset.warranty.end_date >= date.today()
        if asset.warranty_expiry_date:
            return asset.warranty_expiry_date >= date.today()
        return False

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=14 * mm,
        rightMargin=14 * mm,
        topMargin=14 * mm,
        bottomMargin=14 * mm,
    )

    styles = getSampleStyleSheet()
    elements = []

    purchase_date = _fmt_date(asset.purchase_date)
    lifecycle_line = f"Lifecycle Window: {purchase_date} to {datetime.utcnow().strftime('%Y-%m-%d')}"

    elements.append(Paragraph(f"<b>{report_title}</b>", styles["Title"]))
    elements.append(Paragraph(f"Asset: {asset.asset_tag}", styles["Heading3"]))
    elements.append(
        Paragraph(
            f"Generated by: {generated_by} | Generated at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            styles["Normal"],
        )
    )
    elements.append(Paragraph(lifecycle_line, styles["Normal"]))
    elements.append(Spacer(1, 8))

    if fields.include_asset_overview:
        elements.append(Paragraph("<b>Asset Overview</b>", styles["Heading3"]))
        overview_rows = [
            ["Asset Tag", asset.asset_tag],
            ["Serial Number", asset.serial_number or "-"],
            ["Category", asset.category.name if asset.category else "-"],
            ["Model", f"{asset.manufacturer} {asset.model_name}"],
            ["Current Status", asset.status],
            ["Location", asset.location or "-"],
            ["Supplier", asset.supplier.name if asset.supplier else "-"],
            ["Purchase Date", purchase_date],
        ]
        overview_table = Table(overview_rows, colWidths=[45 * mm, 130 * mm])
        overview_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        elements.append(overview_table)
        elements.append(Spacer(1, 8))

    if fields.include_assignment_snapshot:
        elements.append(Paragraph("<b>Current Assignment</b>", styles["Heading3"]))
        assigned_name = asset.employee.name if asset.employee else "Unassigned"
        assigned_email = asset.employee.email if asset.employee else "-"
        assigned_department = asset.employee.department if asset.employee else "-"
        snapshot_table = Table(
            [
                ["Assigned To", assigned_name],
                ["Email", assigned_email],
                ["Department", assigned_department],
            ],
            colWidths=[45 * mm, 130 * mm],
        )
        snapshot_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ]
            )
        )
        elements.append(snapshot_table)
        elements.append(Spacer(1, 8))

    if fields.include_financial_details:
        elements.append(Paragraph("<b>Financial Details</b>", styles["Heading3"]))
        finance_table = Table(
            [
                ["Purchase Price", _fmt_money(asset.purchase_price)],
                ["Warranty Months", str(asset.warranty_months or "-")],
            ],
            colWidths=[45 * mm, 130 * mm],
        )
        finance_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ]
            )
        )
        elements.append(finance_table)
        elements.append(Spacer(1, 8))

    if fields.include_warranty_details:
        elements.append(Paragraph("<b>Warranty Details</b>", styles["Heading3"]))
        if asset.warranty:
            warranty_rows = [
                ["Provider", asset.warranty.provider_name or "-"],
                ["Duration", f"{asset.warranty.duration_months} months"],
                ["Start Date", _fmt_date(asset.warranty.start_date)],
                ["End Date", _fmt_date(asset.warranty.end_date)],
                ["Status", "Active" if _is_warranty_active() else "Expired"],
            ]
            warranty_table = Table(warranty_rows, colWidths=[45 * mm, 130 * mm])
            warranty_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#ecfeff")),
                        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ]
                )
            )
            elements.append(warranty_table)
            if asset.warranty.terms_conditions:
                elements.append(Spacer(1, 4))
                elements.append(Paragraph(f"Terms: {asset.warranty.terms_conditions}", styles["Normal"]))
        else:
            elements.append(Paragraph("No warranty record available.", styles["Normal"]))
        elements.append(Spacer(1, 8))

    if fields.include_assignment_history:
        elements.append(Paragraph("<b>Assignment History</b>", styles["Heading3"]))
        history_rows = [["Employee", "Department", "Assigned At", "Unassigned At", "State"]]
        for item in assignment_history:
            history_rows.append(
                [
                    item.employee_name or "-",
                    item.employee_department or "-",
                    _fmt_date(item.assigned_at),
                    _fmt_date(item.unassigned_at),
                    "Current" if item.unassigned_at is None else "Closed",
                ]
            )
        if len(history_rows) == 1:
            history_rows.append(["No assignment history", "-", "-", "-", "-"])
        history_table = Table(history_rows, repeatRows=1)
        history_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                ]
            )
        )
        elements.append(history_table)
        elements.append(Spacer(1, 8))

    if fields.include_component_history:
        elements.append(Paragraph("<b>Hardware Component History</b>", styles["Heading3"]))
        headers = ["Component", "Category", "Installed", "Removed", "State"]
        if fields.include_component_specs:
            headers.append("Specifications")
        component_rows = [headers]
        for item in component_history:
            component = item.component
            row = [
                component.name if component else "Unknown",
                component.category if component else "-",
                _fmt_date(item.installed_date),
                _fmt_date(item.removed_date),
                "Installed" if item.removed_date is None else "Removed",
            ]
            if fields.include_component_specs:
                row.append((component.specifications[:70] + "...") if component and component.specifications and len(component.specifications) > 70 else (component.specifications if component and component.specifications else "-"))
            component_rows.append(row)
        if len(component_rows) == 1:
            component_rows.append(["No components recorded", "-", "-", "-", "-"] + (["-"] if fields.include_component_specs else []))

        components_table = Table(component_rows, repeatRows=1)
        components_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#14532d")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#bbf7d0")),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0fdf4")]),
                ]
            )
        )
        elements.append(components_table)
        elements.append(Spacer(1, 8))

    if fields.include_notes:
        elements.append(Paragraph("<b>Asset Notes</b>", styles["Heading3"]))
        elements.append(Paragraph(asset.notes or "No notes recorded.", styles["Normal"]))

    doc.build(elements)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf


# ============== Category Endpoints ==============

@router.get("/categories", response_model=List[CategoryResponse])
def get_categories(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get all categories for dropdown selection."""
    categories = db.query(Category).order_by(Category.name).all()
    return categories


@router.post("/categories", response_model=CategoryResponse)
def create_category(
    category_data: CategoryCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Create a new category."""
    # Check if category already exists
    existing = db.query(Category).filter(Category.name == category_data.name).first()
    if existing:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Category with this name already exists"
        )
    
    db_category = Category(**category_data.model_dump())
    db.add(db_category)
    db.commit()
    db.refresh(db_category)
    return db_category


# ============== Dashboard Endpoints ==============

@router.get("/dashboard/metrics", response_model=DashboardMetrics)
def get_dashboard_metrics(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get dashboard metrics for asset counts by status."""
    total = db.query(func.count(Asset.id)).scalar() or 0
    deployed = db.query(func.count(Asset.id)).filter(Asset.status == "Deployed").scalar() or 0
    available = db.query(func.count(Asset.id)).filter(Asset.status == "Available").scalar() or 0
    in_maintenance = db.query(func.count(Asset.id)).filter(Asset.status == "In Maintenance").scalar() or 0
    retired = db.query(func.count(Asset.id)).filter(Asset.status == "Retired").scalar() or 0
    
    return DashboardMetrics(
        total_assets=total,
        deployed=deployed,
        available=available,
        in_maintenance=in_maintenance,
        retired=retired
    )


@router.get("/dashboard/expiring-warranties", response_model=List[WarrantyAlert])
def get_expiring_warranties(
    days: int = Query(30, ge=1, le=365, description="Number of days to look ahead"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get assets with warranties expiring within the specified number of days."""
    today = date.today()
    future_date = today + timedelta(days=days)
    
    assets = db.query(Asset).filter(
        Asset.warranty_expiry_date != None,
        Asset.warranty_expiry_date >= today,
        Asset.warranty_expiry_date <= future_date,
        Asset.status != "Retired",
        Asset.status != "Disposed"
    ).order_by(Asset.warranty_expiry_date).all()
    
    alerts = []
    for asset in assets:
        days_remaining = (asset.warranty_expiry_date - today).days
        alerts.append(WarrantyAlert(
            id=asset.id,
            asset_tag=asset.asset_tag,
            model_name=asset.model_name,
            manufacturer=asset.manufacturer,
            warranty_expiry_date=asset.warranty_expiry_date,
            days_remaining=days_remaining,
            status=asset.status
        ))
    
    return alerts


# ============== Asset CRUD Endpoints ==============

@router.get("/", response_model=List[AssetResponse])
def get_assets(
    status: Optional[str] = Query(None, description="Filter by status"),
    category_id: Optional[int] = Query(None, description="Filter by category ID"),
    search: Optional[str] = Query(None, description="Search by asset tag or serial number"),
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=500),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get all assets with optional filtering.
    
    - **status**: Filter by asset status (Available, Deployed, In Maintenance, Retired, Disposed)
    - **category_id**: Filter by category
    - **search**: Search by asset tag or serial number
    """
    query = db.query(Asset).join(Category)
    
    # Apply filters
    if status:
        query = query.filter(Asset.status == status)
    if category_id:
        query = query.filter(Asset.category_id == category_id)
    if search:
        search_term = f"%{search}%"
        query = query.filter(
            (Asset.asset_tag.ilike(search_term)) |
            (Asset.serial_number.ilike(search_term))
        )
    
    # Order by created date descending
    query = query.order_by(Asset.created_at.desc())
    
    # Execute with pagination
    assets = query.offset(skip).limit(limit).all()
    
    return assets


@router.post("/reports/pdf")
def generate_assets_pdf_report(
    report_request: AssetReportRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Generate a PDF report for assets using ReportLab."""

    if report_request.start_date and report_request.end_date and report_request.start_date > report_request.end_date:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Start date cannot be after end date"
        )

    query = db.query(Asset).join(Category)

    if report_request.status and report_request.status.lower() != "all":
        query = query.filter(Asset.status == report_request.status)

    if report_request.start_date:
        query = query.filter(Asset.purchase_date >= report_request.start_date)
    if report_request.end_date:
        query = query.filter(Asset.purchase_date <= report_request.end_date)

    assets = query.order_by(Asset.created_at.desc()).all()

    total_value = sum(asset.purchase_price or 0 for asset in assets)
    assigned_assets = sum(1 for asset in assets if asset.employee_id is not None)
    unassigned_assets = len(assets) - assigned_assets

    status_counts = {
        "Available": 0,
        "Deployed": 0,
        "In Maintenance": 0,
        "Retired": 0,
        "Disposed": 0,
    }
    for asset in assets:
        if asset.status in status_counts:
            status_counts[asset.status] += 1

    report_title = report_request.report_title or "Asset Inventory Report"

    try:
        pdf_bytes = _generate_assets_pdf_with_reportlab(
            report_title=report_title,
            generated_by=current_user.username,
            filters={
                "status": report_request.status,
                "start_date": report_request.start_date,
                "end_date": report_request.end_date,
            },
            fields=report_request.fields,
            assets=assets,
            summary={
                "total_assets": len(assets),
                "assigned_assets": assigned_assets,
                "unassigned_assets": unassigned_assets,
                "total_value": total_value,
                "status_counts": status_counts,
            },
        )
    except Exception as exc:
        logger.exception("ReportLab PDF generation failed")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"PDF generation failed: {exc}"
        ) from exc

    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"asset_report_{timestamp}.pdf"

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"'
        },
    )


@router.post("/{asset_id}/reports/pdf")
def generate_asset_profile_pdf_report(
    asset_id: int,
    report_request: AssetProfileReportRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Generate a single asset lifecycle PDF report with selectable sections."""
    asset = db.query(Asset).filter(Asset.id == asset_id).first()
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Asset not found",
        )

    assignment_history = (
        db.query(AssignmentHistory)
        .filter(AssignmentHistory.asset_id == asset_id)
        .order_by(AssignmentHistory.assigned_at.desc())
        .all()
    )

    component_history = (
        db.query(AssetComponentHistory)
        .filter(AssetComponentHistory.asset_id == asset_id)
        .order_by(AssetComponentHistory.installed_date.desc())
        .all()
    )

    report_title = report_request.report_title or f"Asset Lifecycle Report - {asset.asset_tag}"

    try:
        pdf_bytes = _generate_asset_profile_pdf_with_reportlab(
            report_title=report_title,
            generated_by=current_user.username,
            asset=asset,
            assignment_history=assignment_history,
            component_history=component_history,
            fields=report_request.fields,
        )
    except Exception as exc:
        logger.exception("Asset profile PDF generation failed")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"PDF generation failed: {exc}",
        ) from exc

    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    safe_tag = (asset.asset_tag or "asset").replace(" ", "_")
    filename = f"asset_profile_report_{safe_tag}_{timestamp}.pdf"

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.post("/", response_model=AssetResponse, status_code=status.HTTP_201_CREATED)
def create_asset(
    asset_data: AssetCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Create a new asset with optional warranty.
    
    If warranty object is provided, creates a separate warranty record linked to the asset.
    The warranty_expiry_date is automatically calculated by adding warranty_months to purchase_date.
    """
    # Check if asset tag already exists
    existing = db.query(Asset).filter(Asset.asset_tag == asset_data.asset_tag).first()
    if existing:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Asset with this asset tag already exists"
        )
    
    # Verify category exists
    category = db.query(Category).filter(Category.id == asset_data.category_id).first()
    if not category:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Category not found"
        )
    
    # Verify supplier exists if provided
    if asset_data.supplier_id:
        supplier = db.query(Supplier).filter(Supplier.id == asset_data.supplier_id).first()
        if not supplier:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Supplier not found"
            )
    
    # Calculate legacy warranty expiry date
    warranty_expiry_date = None
    if asset_data.purchase_date and asset_data.warranty_months:
        warranty_expiry_date = asset_data.purchase_date + relativedelta(months=asset_data.warranty_months)
    
    # Extract warranty data before creating asset
    warranty_data = asset_data.warranty
    asset_dict = asset_data.model_dump(exclude={'warranty'})
    
    # Create asset
    db_asset = Asset(
        **asset_dict,
        warranty_expiry_date=warranty_expiry_date
    )
    
    db.add(db_asset)
    db.flush()  # Get the asset ID without committing
    
    # Create warranty record if warranty data provided
    if warranty_data:
        # Calculate warranty end date
        warranty_end_date = warranty_data.start_date + relativedelta(months=warranty_data.duration_months)
        
        db_warranty = Warranty(
            asset_id=db_asset.id,
            provider_name=warranty_data.provider_name,
            duration_months=warranty_data.duration_months,
            start_date=warranty_data.start_date,
            end_date=warranty_end_date,
            terms_conditions=warranty_data.terms_conditions
        )
        db.add(db_warranty)
    
    db.commit()
    db.refresh(db_asset)
    
    return db_asset


@router.get("/{asset_id}", response_model=AssetResponse)
def get_asset(
    asset_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get a single asset by ID."""
    asset = db.query(Asset).filter(Asset.id == asset_id).first()
    
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Asset not found"
        )
    
    return asset


@router.put("/{asset_id}", response_model=AssetResponse)
def update_asset(
    asset_id: int,
    asset_data: AssetUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Update an existing asset."""
    asset = db.query(Asset).filter(Asset.id == asset_id).first()
    
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Asset not found"
        )
    
    # Check for duplicate asset tag if being updated
    if asset_data.asset_tag and asset_data.asset_tag != asset.asset_tag:
        existing = db.query(Asset).filter(Asset.asset_tag == asset_data.asset_tag).first()
        if existing:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Asset with this asset tag already exists"
            )
    
    # Update fields
    update_data = asset_data.model_dump(exclude_unset=True)
    
    # If status is changing to Available, Retired, or Disposed, auto-unassign employee
    new_status = update_data.get('status')
    if new_status in ['Available', 'Retired', 'Disposed'] and asset.employee_id is not None:
        # Close out the current assignment history record
        current_history = db.query(AssignmentHistory).filter(
            AssignmentHistory.asset_id == asset_id,
            AssignmentHistory.employee_id == asset.employee_id,
            AssignmentHistory.unassigned_at == None
        ).first()
        if current_history:
            current_history.unassigned_at = datetime.utcnow()
        
        update_data['employee_id'] = None
        update_data['assigned_to'] = None
    
    # Recalculate warranty expiry date if purchase_date or warranty_months changed
    purchase_date = update_data.get('purchase_date', asset.purchase_date)
    warranty_months = update_data.get('warranty_months', asset.warranty_months)
    
    if 'purchase_date' in update_data or 'warranty_months' in update_data:
        if purchase_date and warranty_months:
            update_data['warranty_expiry_date'] = purchase_date + relativedelta(months=warranty_months)
    
    for key, value in update_data.items():
        setattr(asset, key, value)
    
    db.commit()
    db.refresh(asset)
    
    return asset


@router.delete("/{asset_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_asset(
    asset_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Delete an asset."""
    asset = db.query(Asset).filter(Asset.id == asset_id).first()
    
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Asset not found"
        )
    
    db.delete(asset)
    db.commit()
    
    return None


# ============== Asset Assignment ==============

@router.post("/{asset_id}/assign", response_model=AssetResponse)
def assign_asset(
    asset_id: int,
    assignment: AssetAssign,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Assign or unassign an asset to an employee.
    
    - If employee_id is provided, assigns the asset to that employee and sets status to "Deployed"
    - If employee_id is null/None, unassigns the asset and sets status to "Available"
    """
    asset = db.query(Asset).filter(Asset.id == asset_id).first()
    
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Asset not found"
        )
    
    # If asset is currently assigned, close out that assignment history record
    is_actual_unassign = assignment.employee_id is None and asset.employee_id is not None
    if is_actual_unassign and not (assignment.unassign_reason and assignment.unassign_reason.strip()):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Unassign reason is required"
        )

    if asset.employee_id is not None:
        current_history = db.query(AssignmentHistory).filter(
            AssignmentHistory.asset_id == asset_id,
            AssignmentHistory.employee_id == asset.employee_id,
            AssignmentHistory.unassigned_at == None
        ).first()
        if current_history:
            current_history.unassigned_at = datetime.utcnow()
            if assignment.employee_id is None:
                current_history.unassign_reason = assignment.unassign_reason.strip() if assignment.unassign_reason else None
            else:
                current_history.unassign_reason = "Reassigned to another employee"
    
    if assignment.employee_id is not None:
        # Assigning to an employee
        employee = db.query(Employee).filter(Employee.id == assignment.employee_id).first()
        if not employee:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Employee not found"
            )
        
        # Create new assignment history record
        history_record = AssignmentHistory(
            asset_id=asset_id,
            employee_id=employee.id,
            employee_name=employee.name,
            employee_email=employee.email,
            employee_department=employee.department,
            assigned_at=datetime.utcnow()
        )
        db.add(history_record)
        
        asset.employee_id = assignment.employee_id
        asset.assigned_to = employee.name  # Store employee name for reference
        asset.status = "Deployed"
    else:
        # Unassigning - set employee_id to None and status to Available
        asset.employee_id = None
        asset.assigned_to = None
        asset.status = "Available"
    
    db.commit()
    db.refresh(asset)
    
    return asset


@router.get("/{asset_id}/history", response_model=List[AssignmentHistoryResponse])
def get_assignment_history(
    asset_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get the assignment history for an asset.
    
    Returns all past and current assignments in descending order (most recent first).
    """
    asset = db.query(Asset).filter(Asset.id == asset_id).first()
    
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Asset not found"
        )
    
    history = db.query(AssignmentHistory).filter(
        AssignmentHistory.asset_id == asset_id
    ).order_by(AssignmentHistory.assigned_at.desc()).all()
    
    return history


# ============== Component Installation ==============

@router.get("/{asset_id}/components", response_model=List[AssetComponentHistoryResponse])
def get_asset_components(
    asset_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get the component installation history for an asset.
    
    Returns all components that have been installed in this asset (past and current).
    """
    asset = db.query(Asset).filter(Asset.id == asset_id).first()
    
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Asset not found"
        )
    
    history = db.query(AssetComponentHistory).filter(
        AssetComponentHistory.asset_id == asset_id
    ).order_by(AssetComponentHistory.installed_date.desc()).all()
    
    return history


@router.post("/{asset_id}/install-component", response_model=AssetComponentHistoryResponse)
def install_component(
    asset_id: int,
    install_data: InstallComponentRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Install a component into an asset.
    
    - Updates the component's status to "Installed"
    - Creates a record in the asset component history
    """
    # Verify asset exists
    asset = db.query(Asset).filter(Asset.id == asset_id).first()
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Asset not found"
        )
    
    # Verify component exists
    component = db.query(Component).filter(Component.id == install_data.component_id).first()
    if not component:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Component not found"
        )
    
    # Check component is available
    if component.status != ComponentStatus.AVAILABLE.value:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Component is not available for installation. Current status: {component.status}"
        )
    
    # Update component status to Installed
    component.status = ComponentStatus.INSTALLED.value
    
    # Create history record
    history_record = AssetComponentHistory(
        asset_id=asset_id,
        component_id=install_data.component_id,
        installed_date=datetime.utcnow(),
        installed_by=install_data.installed_by or current_user.username,
        notes=install_data.notes
    )
    db.add(history_record)
    
    db.commit()
    db.refresh(history_record)
    
    return history_record


@router.post("/{asset_id}/remove-component/{history_id}", response_model=AssetComponentHistoryResponse)
def remove_component(
    asset_id: int,
    history_id: int,
    remove_data: RemoveComponentRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Remove a component from an asset.
    
    - Updates the history record with removal date and reason
    - Sets the component status back to "Available"
    """
    # Verify asset exists
    asset = db.query(Asset).filter(Asset.id == asset_id).first()
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Asset not found"
        )
    
    # Get the history record
    history_record = db.query(AssetComponentHistory).filter(
        AssetComponentHistory.id == history_id,
        AssetComponentHistory.asset_id == asset_id
    ).first()
    
    if not history_record:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Component installation record not found"
        )
    
    if history_record.removed_date is not None:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Component has already been removed from this asset"
        )
    
    # Update history record
    history_record.removed_date = datetime.utcnow()
    history_record.removal_reason = remove_data.removal_reason
    
    # Update component status back to Available
    component = db.query(Component).filter(Component.id == history_record.component_id).first()
    if component:
        component.status = ComponentStatus.AVAILABLE.value
    
    db.commit()
    db.refresh(history_record)
    
    return history_record


# ============== Seed Categories (Development Helper) ==============

@router.post("/seed-categories", response_model=List[CategoryResponse])
def seed_categories(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Seed default categories (for development/setup)."""
    default_categories = [
        {"name": "Laptop", "description": "Portable computers"},
        {"name": "Desktop", "description": "Desktop computers and workstations"},
        {"name": "Monitor", "description": "Display monitors"},
        {"name": "Printer", "description": "Printers and multifunction devices"},
        {"name": "Router", "description": "Network routers"},
        {"name": "Switch", "description": "Network switches"},
        {"name": "Server", "description": "Servers and storage"},
        {"name": "Scanner", "description": "Document scanners"},
        {"name": "Keyboard", "description": "Keyboards and input devices"},
        {"name": "Mouse", "description": "Mice and pointing devices"},
        {"name": "Headset", "description": "Headsets and audio devices"},
        {"name": "Other", "description": "Other IT equipment"},
    ]
    
    created_categories = []
    for cat_data in default_categories:
        existing = db.query(Category).filter(Category.name == cat_data["name"]).first()
        if not existing:
            category = Category(**cat_data)
            db.add(category)
            db.commit()
            db.refresh(category)
            created_categories.append(category)
        else:
            created_categories.append(existing)
    
    return created_categories
